### ISSUE TITLE
Connection HTTP Status for Valet served site

### ISSUE THREAD

**Issue by SimonBarrettACT** [Hi-Folks/lara-lens#12]
When running `php artisan laralens:diagnostic` on a domain served by Valet, produces an error that the **domain name is not found**.

**Comment by SimonBarrettACT** [comment]
Fixed this issue by adding 127.0.1.

![](https://user-images.githubusercontent.com/57679318/89787752-ede18f00-db15-11ea-9b67-24e04a8dc7e4.png)

**Comment by roberto-butti** [comment]
Great, thank you for the feedback.
I would like also to replicate some edge cases. or some missconfigured situation.
Which is the value in your APP_URL in .env ?
It was an untracked exception or something like : 
<img width="744" alt="Screenshot 2020-08-10 at 15 33 07" src="https://user-images.githubusercontent.com/678434/89788200-128e3480-db1f-11ea-9de9-55a959821bce.png">

**Comment by SimonBarrettACT** [comment]
Hi Roberto,

Thanks for the reponse.

I have closed the issue as I was able to fix it by adding 127.0.0.1 to my DNS.


Regards

Simon Barrett

________________________________
