### ISSUE TITLE
Seems to be an extra comma before closing bracket?

### ISSUE THREAD

**Issue by appml** [Hi-Folks/lara-lens#17]
https://github.com/Hi-Folks/lara-lens/blob/cb8973d84ef66d5ef5aff4dfdd5b931c932c7237/src/Lens/Traits/DatabaseLens.php#L54

https://github.com/Hi-Folks/lara-lens/blob/cb8973d84ef66d5ef5aff4dfdd5b931c932c7237/src/Lens/Traits/DatabaseLens.php#L131

These lines are throwing exception for me.  It seems the trailing comma is the problem.

**Comment by roberto-butti** [comment]
I see, thank you for the feedback!

**Comment by roberto-butti** [comment]
I just released v0.1.16.
Thanks to your feedback, @appml , i added also a syntax checker during CICD.
Let me know if this release fixes also on your side.

**Comment by appml** [comment]
@roberto-butti Thanks a lot, it works fine now!  A very useful package.
