### ISSUE TITLE
Read prefix config parameter from .env

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/lara-lens#30]
Read _prefix_ config parameter from .env.

In config/config.php we have some configuration for Laralens:
```
return [
    'prefix' => 'laralens', // URL prefix (default=laralens)
    'middleware' => ['web'], // middleware to use (default=web)
    'web-enabled' => 'off' // Activate web view (default=off)
];
```

i think is better to read the values from .env (in this case the user could have different configurations that are environment based)
```
'prefix' => env('LARALENS_PREFIX', 'off');
```

### Recap
.env parameter: LARALENS_PREFIX (string)
Default: 'laralens'

### Documentation
https://laravel.com/docs/8.x/configuration#retrieving-environment-configuration

**Comment by JexPY** [comment]
Hello @roberto-butti, could you assign this easy fix to me? Thanks.

**Comment by roberto-butti** [comment]
> Hello @roberto-butti, could you assign this easy fix to me? Thanks.

sure ! Thank you!!!

**Comment by JexPY** [comment]
@roberto-butti, I created pr [](https://github.com/Hi-Folks/lara-lens/pull/32) here if you like this fix I could create second one for 'middleware'. Also I have question about branches as I see you have created master and develop branch, but develop is not updated for more than 1 month that's why I created pr for master, did I choose the right one?

**Comment by roberto-butti** [comment]
Good question @JexPY . Exactly the right branch is _master_ so , it is ok to open a PR on _master_ branch.  Thank you for the feedback, I think that I need to clarify this on Contributing file https://github.com/Hi-Folks/lara-lens/blob/master/CONTRIBUTING.md . Thank you.

**Comment by JexPY** [comment]
@roberto-butti No problem. Thank you. I also did not know how to assign this issue to pull request so that stayed open. I will try to assign next issue to new pr.

**Comment by roberto-butti** [comment]
I'm testing also the master branch after the merge. It looks good.
Thank you for your support @JexPY 
I'm going to close this issue.
