### ISSUE TITLE
Read middleware config parameter from .env

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/lara-lens#31]
Read _middleware_ config parameter from .env.

In config/config.php we have some configuration for Laralens:
```
return [
    'prefix' => 'laralens', // URL prefix (default=laralens)
    'middleware' => ['web'], // middleware to use (default=web)
    'web-enabled' => 'off' // Activate web view (default=off)
];
```

i think is better to read the values from .env (in this case the user could have different configurations that are environment based)
```
'middleware' => env('LARALENS_MIDDLEWARE', ['web']);
```

### Recap
.env parameter: LARALENS_MIDDLEWARE (array)
Default: ['web']

### Documentation
https://laravel.com/docs/8.x/configuration#retrieving-environment-configuration

**Comment by arthurkay** [comment]
Are the environmental variables you speak of the ones in the app/config.php or there are others as well?

**Comment by roberto-butti** [comment]
i'm referring to config/config.php in the package. Once in your Laravel app publish the config is copied to config/lara-lens.php
I think that this issues is picked by @JexPY

**Comment by JexPY** [comment]
@roberto-butti  PR is created for alrady 1 hour [https://github.com/Hi-Folks/lara-lens/pull/33](https://github.com/Hi-Folks/lara-lens/pull/33). Thanks.

**Comment by roberto-butti** [comment]
> @roberto-butti PR is created for alrady 1 hour #33. Thanks.

I see, I need to test it a little bit more, because the array (in the .env file) could not be so easy liike number or string.

**Comment by arthurkay** [comment]
> i'm referring to config/config.php in the package. Once in your Laravel app publish the config is copied to config/lara-lens.php
> I think that this issues is picked by @JexPY

Alright, thanks, saw that late.

**Comment by JexPY** [comment]
@roberto-butti  We can add validation for array and values to not crash configuration?

**Comment by roberto-butti** [comment]
I'm looking for the best solutoin in order to define an array in .env file.
For now, i see that we could have 2 options:

1. store in .env a string with terms separated by a char for example ",". in this case we could have in .env:

```
LARAVEL_MIDDLEWARE="value1,value2"
```
in this case when you read a string via env() yoou need to explode the string explode(',', env(LARAVEL_MIDDLEWARE, 'web')

2. store in .env a string with json syntax. for example:

```
LARAVEL_MIDDLEWARE='["value1","value2"]'
```
in this case when you read a string via env() you need to use json_decode()

what do you think?

**Comment by JexPY** [comment]
Hello @roberto-butti, I got your opinion, and guess that 1 will be clean approach, I will have one question before implementing if we are working with laravel's package would it be bad if we will use 
```
use Illuminate\Support\Str;

Str::of('value1,value2')->explode(',');
```

**Comment by roberto-butti** [comment]
hi @JexPY , this package is strictly related with Laravel so you can use Str package. The only thing that you need to be sure that the method that you want to use from Str is supported by Laravel 6, 7 ,and 8.

**Comment by JexPY** [comment]
@roberto-butti, yes I know that they added helper functions from 6th release and as I see from package.json, lara-lens supports [https://github.com/Hi-Folks/lara-lens/blob/master/composer.json#L27](url) and php ^7.2 so does not this means that only laravel ^6 is supported?

**Comment by JexPY** [comment]
@roberto-butti New pr check when you will have time.

**Comment by roberto-butti** [comment]
Hi @JexPY , i merged it into master. 
I'm testing a little bit with multiple confugurations ("web,auth" and "web,auth.basic" and ... )
It looks great.

**Comment by roberto-butti** [comment]
The only thing that i'm still investigating about, is the separator "," (in the .env file for LARALENS_MIDDLEWARE).
I'm thinking about a valid syntax foor middleware: "can:update,post" ( https://laravel.com/docs/8.x/authorization#via-middleware )

**Comment by roberto-butti** [comment]
I'm going to close this issue, thank you @JexPY !!! 🥳 

For managing "separator" issue, I opened a specific new issue: #34 , tagged as Hacktoberfest.
