### ISSUE TITLE
Change values saparator in config/config.php for LARALENS_MIDDLEWARE

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/lara-lens#34]
In LARALENS_MIDDLEWARE (.env variables) you can specify multiple values like: 
```
LARALENS_MIDDLEWARE="web,auth.basic"
```

In this case to access to laralens web url (LARALENS_PREFIX) you have 2 middlewares: web and auth.basic.

In config/config.php , **change separator from , to ;** because "," is a valid character for specifing a middleware.

**Comment by Zuruckt** [comment]
Hi, I would like to work on this too =)

This means that .env parameter syntax is going to be `LARALENS_MIDDLEWARE="web;auth.basic"`or should the config.php replace the commas with **;**?
