### ISSUE TITLE
Documentation: add LARALENS_* parameters in readme

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/lara-lens#35]
In readme file, in Web PAge section , add some information about the usage of .env parameters.
The .env parameters are:
LARALENS_WEB_ENABLED="on"
LARALENS_PREFIX="test-env"
LARALENS_MIDDLEWARE="web,auth.basic"

LARALENS_WEB_ENABLED: enable/disable Web report
LARALENS_PREFIX: path prefix in order to access to the Web report via web browser
LARALENS_MIDDLEWARE: middleware to use when the user access to Web page (usually "web").

**Comment by Zuruckt** [comment]
Hey can you assign this to me?

**Comment by roberto-butti** [comment]
> Hey can you assign this to me?

Sure! Thank you!
