### ISSUE TITLE
Banner graphics has a typo

### ISSUE THREAD

**Issue by bomas13** [Hi-Folks/lara-lens#6]
Hi,

your banner graphic claims that this is an artisan `commad`

Greetings,
Thomas

**Comment by roberto-butti** [comment]
Thank you for the feedback!

**Comment by roberto-butti** [comment]
I re-open the issue because there is a "strange" behaviour. The banner image is update on the git repo, but the Git UI (and so the readme) doens't reflect the updated image. (probably it takes some time to invalidate cache , or better, i need a coffee before to open my laptop).

**Comment by roberto-butti** [comment]
Now also the UI is updated.
