### ISSUE TITLE
Getting server versionen produces error

### ISSUE THREAD

**Issue by red-freak** [Hi-Folks/lara-lens#8]
If you are using a mongodb (`Jenssegers\Mongodb\Connection`) as dbconnection the requesting of the PDO in line 110 of LaraLens.php is failing 'cuz getPDO() is null.

Maybe checking the `getPdo()` on null would be a solution or a different behavior for `$dbconnection->getDriverName() === 'mongodb'`

**Comment by red-freak** [comment]
The command also fails if you do net have setup a dbconnection. In my case we have sperated Vue-Frontend and a laravel backend. For the frontend there is no user table. there is no table, no db-connection.

And it also only checks the first connection, what seems to be ok but could be a problem.

**Comment by roberto-butti** [comment]
Hi @Red-Freak , thank you for the feedback.
Which version of LaraLens are you using?
I improved a little bit the db connection check with the latest 2 versions (last one is 0.1.13).
Anyway, i will try to simulate your scenario.
Thank you

**Comment by red-freak** [comment]
I use the current version 0.1.13.

Thanks a lot for this tool!

**Comment by roberto-butti** [comment]
I'm approaching to this issue in this way.
### For the next release (0.1.14)
Some checks, are performed via PDO. For databases that are not supported by PDO, in 0.1.14 I will skip these checks. (anyway, as non PDO database you will have information for runtime configuration and configured parameters)
### For the next major release (0.2.x)
I will add some specific not PDO check specific for some db (like mongo).

**Comment by roberto-butti** [comment]
Investigating a little bit about this i found a small bug in Jenssegers\Mongodb when you have a not valid DB_CONNECTION.
to reproduce this:
- install Jenssegers\Mongodb
- configure DB_CONNNECTION as "fsdkfjfl" (a random name that not exists in app['config']['database.connections'])
mongo db is used also for registering failed jobs for the queue.
In this case the MongodbQueueServiceProvider::registerFailedJobServices try to access directly to the db connection.
I think i will open a new issue for Jenssegers\Mongodb and i will try to open a Merger request.

**Comment by red-freak** [comment]
Thanks a lot. 0.1.14 is giving a warning with a nice hint, that the warning is ok :)
